@startuml

hide empty description

[*] -down-> Start

Start --> Game 

Start : Itt látjuk a toplistát a\njáték indítása előtt

state Game {
	[*] --> Level1
	Level1 -right-> Level2
	Level2 --> Level3
	Level3 --> Level4
	Level4 --> Level1 : Növeljük\na nehézséget

	Level1: Alap szint, rendezetten\nsorakoznak a csirkék
	Level2: Ugyan az, mint az első szint
	Level3: Össze-vissza mozognak a\ncsirkék, közelednek a játékoshoz
	Level4: Rendezett sorokban\nközelednek a játékoshoz
}

Game -right-> GameOver : Játékos veszít
GameOver -up-> Start 

GameOver : Itt adhatjuk meg, hogy milyen\nnév szerepeljen a toplistában 

@enduml